; ============================================================================
; Quiz Battle - question banks (grades 1-5)
; ----------------------------------------------------------------------------
; GENERATED by tools_gen_quiz.py -- edit that script and re-run it, then `make`.
; Font has NO =,+,% ; use words ("plus") and  - / x . : ? !  only.
; Question text <= 18 chars, each answer <= 9, each hint <= 18.
; ============================================================================

; One question entry (14 bytes):
;   quizq QUESTION, CORRECT_INDEX(0-3), NUM_ANSWERS(2-4), ANS0, ANS1, ANS2, ANS3, HINT
MACRO quizq
	dw \1
	db \2
	db \3
	dw \4, \5, \6, \7
	dw \8
ENDM

QuizGradeTable::
	dw Grade1Questions
	db (Grade2Questions - Grade1Questions) / 14
	dw Grade2Questions
	db (Grade3Questions - Grade2Questions) / 14
	dw Grade3Questions
	db (Grade4Questions - Grade3Questions) / 14
	dw Grade4Questions
	db (Grade5Questions - Grade4Questions) / 14
	dw Grade5Questions
	db (QuestionsEnd - Grade5Questions) / 14

Grade1Questions::
	quizq G1Q1, 0, 3, G1Q1A, G1Q1B, G1Q1C, G1Q1C, G1Q1H
	quizq G1Q2, 0, 3, G1Q2A, G1Q2B, G1Q2C, G1Q2C, G1Q2H
	quizq G1Q3, 0, 3, G1Q3A, G1Q3B, G1Q3C, G1Q3C, G1Q3H
	quizq G1Q4, 0, 3, G1Q4A, G1Q4B, G1Q4C, G1Q4C, G1Q4H
	quizq G1Q5, 0, 3, G1Q5A, G1Q5B, G1Q5C, G1Q5C, G1Q5H
	quizq G1Q6, 0, 3, G1Q6A, G1Q6B, G1Q6C, G1Q6C, G1Q6H
	quizq G1Q7, 0, 3, G1Q7A, G1Q7B, G1Q7C, G1Q7C, G1Q7H
	quizq G1Q8, 0, 3, G1Q8A, G1Q8B, G1Q8C, G1Q8C, G1Q8H
	quizq G1Q9, 0, 3, G1Q9A, G1Q9B, G1Q9C, G1Q9C, G1Q9H
	quizq G1Q10, 0, 3, G1Q10A, G1Q10B, G1Q10C, G1Q10C, G1Q10H
	quizq G1Q11, 0, 3, G1Q11A, G1Q11B, G1Q11C, G1Q11C, G1Q11H
	quizq G1Q12, 0, 3, G1Q12A, G1Q12B, G1Q12C, G1Q12C, G1Q12H
	quizq G1Q13, 0, 3, G1Q13A, G1Q13B, G1Q13C, G1Q13C, G1Q13H
	quizq G1Q14, 0, 3, G1Q14A, G1Q14B, G1Q14C, G1Q14C, G1Q14H
	quizq G1Q15, 0, 3, G1Q15A, G1Q15B, G1Q15C, G1Q15C, G1Q15H
	quizq G1Q16, 0, 3, G1Q16A, G1Q16B, G1Q16C, G1Q16C, G1Q16H
	quizq G1Q17, 0, 3, G1Q17A, G1Q17B, G1Q17C, G1Q17C, G1Q17H
	quizq G1Q18, 0, 3, G1Q18A, G1Q18B, G1Q18C, G1Q18C, G1Q18H
	quizq G1Q19, 0, 3, G1Q19A, G1Q19B, G1Q19C, G1Q19C, G1Q19H
	quizq G1Q20, 0, 3, G1Q20A, G1Q20B, G1Q20C, G1Q20C, G1Q20H
	quizq G1Q21, 0, 3, G1Q21A, G1Q21B, G1Q21C, G1Q21C, G1Q21H
	quizq G1Q22, 0, 3, G1Q22A, G1Q22B, G1Q22C, G1Q22C, G1Q22H
	quizq G1Q23, 0, 3, G1Q23A, G1Q23B, G1Q23C, G1Q23C, G1Q23H
	quizq G1Q24, 0, 3, G1Q24A, G1Q24B, G1Q24C, G1Q24C, G1Q24H
	quizq G1Q25, 0, 3, G1Q25A, G1Q25B, G1Q25C, G1Q25C, G1Q25H
	quizq G1Q26, 0, 3, G1Q26A, G1Q26B, G1Q26C, G1Q26C, G1Q26H
	quizq G1Q27, 0, 3, G1Q27A, G1Q27B, G1Q27C, G1Q27C, G1Q27H
	quizq G1Q28, 0, 3, G1Q28A, G1Q28B, G1Q28C, G1Q28C, G1Q28H
	quizq G1Q29, 0, 3, G1Q29A, G1Q29B, G1Q29C, G1Q29C, G1Q29H
	quizq G1Q30, 0, 3, G1Q30A, G1Q30B, G1Q30C, G1Q30C, G1Q30H
	quizq G1Q31, 0, 3, G1Q31A, G1Q31B, G1Q31C, G1Q31C, G1Q31H
	quizq G1Q32, 0, 3, G1Q32A, G1Q32B, G1Q32C, G1Q32C, G1Q32H
	quizq G1Q33, 0, 3, G1Q33A, G1Q33B, G1Q33C, G1Q33C, G1Q33H
	quizq G1Q34, 0, 3, G1Q34A, G1Q34B, G1Q34C, G1Q34C, G1Q34H
	quizq G1Q35, 0, 3, G1Q35A, G1Q35B, G1Q35C, G1Q35C, G1Q35H
	quizq G1Q36, 0, 3, G1Q36A, G1Q36B, G1Q36C, G1Q36C, G1Q36H
	quizq G1Q37, 0, 3, G1Q37A, G1Q37B, G1Q37C, G1Q37C, G1Q37H
	quizq G1Q38, 0, 3, G1Q38A, G1Q38B, G1Q38C, G1Q38C, G1Q38H
	quizq G1Q39, 0, 3, G1Q39A, G1Q39B, G1Q39C, G1Q39C, G1Q39H
	quizq G1Q40, 0, 3, G1Q40A, G1Q40B, G1Q40C, G1Q40C, G1Q40H
	quizq G1Q41, 0, 3, G1Q41A, G1Q41B, G1Q41C, G1Q41C, G1Q41H
	quizq G1Q42, 0, 3, G1Q42A, G1Q42B, G1Q42C, G1Q42C, G1Q42H
	quizq G1Q43, 0, 3, G1Q43A, G1Q43B, G1Q43C, G1Q43C, G1Q43H
	quizq G1Q44, 0, 3, G1Q44A, G1Q44B, G1Q44C, G1Q44C, G1Q44H
	quizq G1Q45, 0, 3, G1Q45A, G1Q45B, G1Q45C, G1Q45C, G1Q45H
	quizq G1Q46, 0, 3, G1Q46A, G1Q46B, G1Q46C, G1Q46C, G1Q46H
	quizq G1Q47, 0, 3, G1Q47A, G1Q47B, G1Q47C, G1Q47C, G1Q47H
	quizq G1Q48, 0, 3, G1Q48A, G1Q48B, G1Q48C, G1Q48C, G1Q48H
	quizq G1Q49, 0, 3, G1Q49A, G1Q49B, G1Q49C, G1Q49C, G1Q49H
	quizq G1Q50, 0, 3, G1Q50A, G1Q50B, G1Q50C, G1Q50C, G1Q50H
	quizq G1Q51, 0, 3, G1Q51A, G1Q51B, G1Q51C, G1Q51C, G1Q51H
	quizq G1Q52, 0, 3, G1Q52A, G1Q52B, G1Q52C, G1Q52C, G1Q52H
	quizq G1Q53, 0, 3, G1Q53A, G1Q53B, G1Q53C, G1Q53C, G1Q53H
	quizq G1Q54, 0, 3, G1Q54A, G1Q54B, G1Q54C, G1Q54C, G1Q54H
	quizq G1Q55, 0, 3, G1Q55A, G1Q55B, G1Q55C, G1Q55C, G1Q55H
	quizq G1Q56, 0, 3, G1Q56A, G1Q56B, G1Q56C, G1Q56C, G1Q56H
	quizq G1Q57, 0, 3, G1Q57A, G1Q57B, G1Q57C, G1Q57C, G1Q57H
	quizq G1Q58, 0, 3, G1Q58A, G1Q58B, G1Q58C, G1Q58C, G1Q58H
	quizq G1Q59, 0, 3, G1Q59A, G1Q59B, G1Q59C, G1Q59C, G1Q59H
	quizq G1Q60, 0, 3, G1Q60A, G1Q60B, G1Q60C, G1Q60C, G1Q60H
	quizq G1Q61, 0, 3, G1Q61A, G1Q61B, G1Q61C, G1Q61C, G1Q61H
	quizq G1Q62, 0, 3, G1Q62A, G1Q62B, G1Q62C, G1Q62C, G1Q62H
	quizq G1Q63, 0, 3, G1Q63A, G1Q63B, G1Q63C, G1Q63C, G1Q63H
	quizq G1Q64, 0, 3, G1Q64A, G1Q64B, G1Q64C, G1Q64C, G1Q64H
	quizq G1Q65, 0, 3, G1Q65A, G1Q65B, G1Q65C, G1Q65C, G1Q65H
	quizq G1Q66, 0, 3, G1Q66A, G1Q66B, G1Q66C, G1Q66C, G1Q66H
	quizq G1Q67, 0, 3, G1Q67A, G1Q67B, G1Q67C, G1Q67C, G1Q67H
	quizq G1Q68, 0, 3, G1Q68A, G1Q68B, G1Q68C, G1Q68C, G1Q68H
	quizq G1Q69, 0, 3, G1Q69A, G1Q69B, G1Q69C, G1Q69C, G1Q69H
	quizq G1Q70, 0, 3, G1Q70A, G1Q70B, G1Q70C, G1Q70C, G1Q70H
	quizq G1Q71, 0, 3, G1Q71A, G1Q71B, G1Q71C, G1Q71C, G1Q71H
	quizq G1Q72, 0, 3, G1Q72A, G1Q72B, G1Q72C, G1Q72C, G1Q72H
	quizq G1Q73, 0, 3, G1Q73A, G1Q73B, G1Q73C, G1Q73C, G1Q73H
	quizq G1Q74, 0, 3, G1Q74A, G1Q74B, G1Q74C, G1Q74C, G1Q74H
	quizq G1Q75, 0, 3, G1Q75A, G1Q75B, G1Q75C, G1Q75C, G1Q75H
	quizq G1Q76, 0, 3, G1Q76A, G1Q76B, G1Q76C, G1Q76C, G1Q76H
	quizq G1Q77, 0, 3, G1Q77A, G1Q77B, G1Q77C, G1Q77C, G1Q77H
	quizq G1Q78, 0, 3, G1Q78A, G1Q78B, G1Q78C, G1Q78C, G1Q78H
	quizq G1Q79, 0, 3, G1Q79A, G1Q79B, G1Q79C, G1Q79C, G1Q79H
	quizq G1Q80, 0, 3, G1Q80A, G1Q80B, G1Q80C, G1Q80C, G1Q80H
	quizq G1Q81, 0, 3, G1Q81A, G1Q81B, G1Q81C, G1Q81C, G1Q81H
	quizq G1Q82, 0, 3, G1Q82A, G1Q82B, G1Q82C, G1Q82C, G1Q82H
	quizq G1Q83, 0, 3, G1Q83A, G1Q83B, G1Q83C, G1Q83C, G1Q83H
	quizq G1Q84, 0, 3, G1Q84A, G1Q84B, G1Q84C, G1Q84C, G1Q84H
	quizq G1Q85, 0, 3, G1Q85A, G1Q85B, G1Q85C, G1Q85C, G1Q85H
	quizq G1Q86, 0, 3, G1Q86A, G1Q86B, G1Q86C, G1Q86C, G1Q86H
	quizq G1Q87, 0, 3, G1Q87A, G1Q87B, G1Q87C, G1Q87C, G1Q87H
	quizq G1Q88, 0, 3, G1Q88A, G1Q88B, G1Q88C, G1Q88C, G1Q88H
	quizq G1Q89, 0, 3, G1Q89A, G1Q89B, G1Q89C, G1Q89C, G1Q89H
	quizq G1Q90, 0, 3, G1Q90A, G1Q90B, G1Q90C, G1Q90C, G1Q90H
	quizq G1Q91, 0, 3, G1Q91A, G1Q91B, G1Q91C, G1Q91C, G1Q91H
	quizq G1Q92, 0, 3, G1Q92A, G1Q92B, G1Q92C, G1Q92C, G1Q92H
	quizq G1Q93, 0, 3, G1Q93A, G1Q93B, G1Q93C, G1Q93C, G1Q93H
Grade2Questions::
	quizq G2Q1, 0, 3, G2Q1A, G2Q1B, G2Q1C, G2Q1C, G2Q1H
	quizq G2Q2, 0, 3, G2Q2A, G2Q2B, G2Q2C, G2Q2C, G2Q2H
	quizq G2Q3, 0, 3, G2Q3A, G2Q3B, G2Q3C, G2Q3C, G2Q3H
	quizq G2Q4, 0, 3, G2Q4A, G2Q4B, G2Q4C, G2Q4C, G2Q4H
	quizq G2Q5, 0, 3, G2Q5A, G2Q5B, G2Q5C, G2Q5C, G2Q5H
	quizq G2Q6, 0, 3, G2Q6A, G2Q6B, G2Q6C, G2Q6C, G2Q6H
	quizq G2Q7, 0, 3, G2Q7A, G2Q7B, G2Q7C, G2Q7C, G2Q7H
	quizq G2Q8, 0, 3, G2Q8A, G2Q8B, G2Q8C, G2Q8C, G2Q8H
	quizq G2Q9, 0, 3, G2Q9A, G2Q9B, G2Q9C, G2Q9C, G2Q9H
	quizq G2Q10, 0, 3, G2Q10A, G2Q10B, G2Q10C, G2Q10C, G2Q10H
	quizq G2Q11, 0, 3, G2Q11A, G2Q11B, G2Q11C, G2Q11C, G2Q11H
	quizq G2Q12, 0, 3, G2Q12A, G2Q12B, G2Q12C, G2Q12C, G2Q12H
	quizq G2Q13, 0, 3, G2Q13A, G2Q13B, G2Q13C, G2Q13C, G2Q13H
	quizq G2Q14, 0, 3, G2Q14A, G2Q14B, G2Q14C, G2Q14C, G2Q14H
	quizq G2Q15, 0, 3, G2Q15A, G2Q15B, G2Q15C, G2Q15C, G2Q15H
	quizq G2Q16, 0, 3, G2Q16A, G2Q16B, G2Q16C, G2Q16C, G2Q16H
	quizq G2Q17, 0, 3, G2Q17A, G2Q17B, G2Q17C, G2Q17C, G2Q17H
	quizq G2Q18, 0, 3, G2Q18A, G2Q18B, G2Q18C, G2Q18C, G2Q18H
	quizq G2Q19, 0, 3, G2Q19A, G2Q19B, G2Q19C, G2Q19C, G2Q19H
	quizq G2Q20, 0, 3, G2Q20A, G2Q20B, G2Q20C, G2Q20C, G2Q20H
	quizq G2Q21, 0, 3, G2Q21A, G2Q21B, G2Q21C, G2Q21C, G2Q21H
	quizq G2Q22, 0, 3, G2Q22A, G2Q22B, G2Q22C, G2Q22C, G2Q22H
	quizq G2Q23, 0, 3, G2Q23A, G2Q23B, G2Q23C, G2Q23C, G2Q23H
	quizq G2Q24, 0, 3, G2Q24A, G2Q24B, G2Q24C, G2Q24C, G2Q24H
	quizq G2Q25, 0, 3, G2Q25A, G2Q25B, G2Q25C, G2Q25C, G2Q25H
	quizq G2Q26, 0, 3, G2Q26A, G2Q26B, G2Q26C, G2Q26C, G2Q26H
	quizq G2Q27, 0, 3, G2Q27A, G2Q27B, G2Q27C, G2Q27C, G2Q27H
	quizq G2Q28, 0, 3, G2Q28A, G2Q28B, G2Q28C, G2Q28C, G2Q28H
	quizq G2Q29, 0, 3, G2Q29A, G2Q29B, G2Q29C, G2Q29C, G2Q29H
	quizq G2Q30, 0, 3, G2Q30A, G2Q30B, G2Q30C, G2Q30C, G2Q30H
	quizq G2Q31, 0, 3, G2Q31A, G2Q31B, G2Q31C, G2Q31C, G2Q31H
	quizq G2Q32, 0, 3, G2Q32A, G2Q32B, G2Q32C, G2Q32C, G2Q32H
Grade3Questions::
	quizq G3Q1, 0, 3, G3Q1A, G3Q1B, G3Q1C, G3Q1C, G3Q1H
	quizq G3Q2, 0, 3, G3Q2A, G3Q2B, G3Q2C, G3Q2C, G3Q2H
	quizq G3Q3, 0, 3, G3Q3A, G3Q3B, G3Q3C, G3Q3C, G3Q3H
	quizq G3Q4, 0, 3, G3Q4A, G3Q4B, G3Q4C, G3Q4C, G3Q4H
	quizq G3Q5, 0, 3, G3Q5A, G3Q5B, G3Q5C, G3Q5C, G3Q5H
	quizq G3Q6, 0, 3, G3Q6A, G3Q6B, G3Q6C, G3Q6C, G3Q6H
	quizq G3Q7, 0, 3, G3Q7A, G3Q7B, G3Q7C, G3Q7C, G3Q7H
	quizq G3Q8, 0, 3, G3Q8A, G3Q8B, G3Q8C, G3Q8C, G3Q8H
	quizq G3Q9, 0, 3, G3Q9A, G3Q9B, G3Q9C, G3Q9C, G3Q9H
	quizq G3Q10, 0, 3, G3Q10A, G3Q10B, G3Q10C, G3Q10C, G3Q10H
	quizq G3Q11, 0, 3, G3Q11A, G3Q11B, G3Q11C, G3Q11C, G3Q11H
	quizq G3Q12, 0, 3, G3Q12A, G3Q12B, G3Q12C, G3Q12C, G3Q12H
	quizq G3Q13, 0, 3, G3Q13A, G3Q13B, G3Q13C, G3Q13C, G3Q13H
	quizq G3Q14, 0, 3, G3Q14A, G3Q14B, G3Q14C, G3Q14C, G3Q14H
	quizq G3Q15, 0, 3, G3Q15A, G3Q15B, G3Q15C, G3Q15C, G3Q15H
	quizq G3Q16, 0, 3, G3Q16A, G3Q16B, G3Q16C, G3Q16C, G3Q16H
	quizq G3Q17, 0, 3, G3Q17A, G3Q17B, G3Q17C, G3Q17C, G3Q17H
	quizq G3Q18, 0, 3, G3Q18A, G3Q18B, G3Q18C, G3Q18C, G3Q18H
	quizq G3Q19, 0, 3, G3Q19A, G3Q19B, G3Q19C, G3Q19C, G3Q19H
	quizq G3Q20, 0, 3, G3Q20A, G3Q20B, G3Q20C, G3Q20C, G3Q20H
	quizq G3Q21, 0, 3, G3Q21A, G3Q21B, G3Q21C, G3Q21C, G3Q21H
	quizq G3Q22, 0, 3, G3Q22A, G3Q22B, G3Q22C, G3Q22C, G3Q22H
	quizq G3Q23, 0, 3, G3Q23A, G3Q23B, G3Q23C, G3Q23C, G3Q23H
	quizq G3Q24, 0, 3, G3Q24A, G3Q24B, G3Q24C, G3Q24C, G3Q24H
	quizq G3Q25, 0, 3, G3Q25A, G3Q25B, G3Q25C, G3Q25C, G3Q25H
	quizq G3Q26, 0, 3, G3Q26A, G3Q26B, G3Q26C, G3Q26C, G3Q26H
	quizq G3Q27, 0, 3, G3Q27A, G3Q27B, G3Q27C, G3Q27C, G3Q27H
	quizq G3Q28, 0, 3, G3Q28A, G3Q28B, G3Q28C, G3Q28C, G3Q28H
	quizq G3Q29, 0, 3, G3Q29A, G3Q29B, G3Q29C, G3Q29C, G3Q29H
	quizq G3Q30, 0, 3, G3Q30A, G3Q30B, G3Q30C, G3Q30C, G3Q30H
	quizq G3Q31, 0, 3, G3Q31A, G3Q31B, G3Q31C, G3Q31C, G3Q31H
	quizq G3Q32, 0, 3, G3Q32A, G3Q32B, G3Q32C, G3Q32C, G3Q32H
	quizq G3Q33, 0, 3, G3Q33A, G3Q33B, G3Q33C, G3Q33C, G3Q33H
	quizq G3Q34, 0, 3, G3Q34A, G3Q34B, G3Q34C, G3Q34C, G3Q34H
	quizq G3Q35, 0, 3, G3Q35A, G3Q35B, G3Q35C, G3Q35C, G3Q35H
	quizq G3Q36, 0, 3, G3Q36A, G3Q36B, G3Q36C, G3Q36C, G3Q36H
	quizq G3Q37, 0, 3, G3Q37A, G3Q37B, G3Q37C, G3Q37C, G3Q37H
	quizq G3Q38, 0, 3, G3Q38A, G3Q38B, G3Q38C, G3Q38C, G3Q38H
	quizq G3Q39, 0, 3, G3Q39A, G3Q39B, G3Q39C, G3Q39C, G3Q39H
	quizq G3Q40, 0, 3, G3Q40A, G3Q40B, G3Q40C, G3Q40C, G3Q40H
	quizq G3Q41, 0, 3, G3Q41A, G3Q41B, G3Q41C, G3Q41C, G3Q41H
	quizq G3Q42, 0, 3, G3Q42A, G3Q42B, G3Q42C, G3Q42C, G3Q42H
	quizq G3Q43, 0, 3, G3Q43A, G3Q43B, G3Q43C, G3Q43C, G3Q43H
	quizq G3Q44, 0, 3, G3Q44A, G3Q44B, G3Q44C, G3Q44C, G3Q44H
	quizq G3Q45, 0, 3, G3Q45A, G3Q45B, G3Q45C, G3Q45C, G3Q45H
	quizq G3Q46, 0, 3, G3Q46A, G3Q46B, G3Q46C, G3Q46C, G3Q46H
	quizq G3Q47, 0, 3, G3Q47A, G3Q47B, G3Q47C, G3Q47C, G3Q47H
	quizq G3Q48, 0, 3, G3Q48A, G3Q48B, G3Q48C, G3Q48C, G3Q48H
	quizq G3Q49, 0, 3, G3Q49A, G3Q49B, G3Q49C, G3Q49C, G3Q49H
	quizq G3Q50, 0, 3, G3Q50A, G3Q50B, G3Q50C, G3Q50C, G3Q50H
Grade4Questions::
	quizq G4Q1, 0, 3, G4Q1A, G4Q1B, G4Q1C, G4Q1C, G4Q1H
	quizq G4Q2, 0, 3, G4Q2A, G4Q2B, G4Q2C, G4Q2C, G4Q2H
	quizq G4Q3, 0, 3, G4Q3A, G4Q3B, G4Q3C, G4Q3C, G4Q3H
	quizq G4Q4, 0, 3, G4Q4A, G4Q4B, G4Q4C, G4Q4C, G4Q4H
	quizq G4Q5, 0, 3, G4Q5A, G4Q5B, G4Q5C, G4Q5C, G4Q5H
	quizq G4Q6, 0, 3, G4Q6A, G4Q6B, G4Q6C, G4Q6C, G4Q6H
	quizq G4Q7, 0, 3, G4Q7A, G4Q7B, G4Q7C, G4Q7C, G4Q7H
	quizq G4Q8, 0, 3, G4Q8A, G4Q8B, G4Q8C, G4Q8C, G4Q8H
	quizq G4Q9, 0, 3, G4Q9A, G4Q9B, G4Q9C, G4Q9C, G4Q9H
	quizq G4Q10, 0, 3, G4Q10A, G4Q10B, G4Q10C, G4Q10C, G4Q10H
	quizq G4Q11, 0, 3, G4Q11A, G4Q11B, G4Q11C, G4Q11C, G4Q11H
	quizq G4Q12, 0, 3, G4Q12A, G4Q12B, G4Q12C, G4Q12C, G4Q12H
	quizq G4Q13, 0, 3, G4Q13A, G4Q13B, G4Q13C, G4Q13C, G4Q13H
	quizq G4Q14, 0, 3, G4Q14A, G4Q14B, G4Q14C, G4Q14C, G4Q14H
	quizq G4Q15, 0, 3, G4Q15A, G4Q15B, G4Q15C, G4Q15C, G4Q15H
	quizq G4Q16, 0, 3, G4Q16A, G4Q16B, G4Q16C, G4Q16C, G4Q16H
	quizq G4Q17, 0, 3, G4Q17A, G4Q17B, G4Q17C, G4Q17C, G4Q17H
	quizq G4Q18, 0, 3, G4Q18A, G4Q18B, G4Q18C, G4Q18C, G4Q18H
	quizq G4Q19, 0, 3, G4Q19A, G4Q19B, G4Q19C, G4Q19C, G4Q19H
	quizq G4Q20, 0, 3, G4Q20A, G4Q20B, G4Q20C, G4Q20C, G4Q20H
	quizq G4Q21, 0, 3, G4Q21A, G4Q21B, G4Q21C, G4Q21C, G4Q21H
Grade5Questions::
	quizq G5Q1, 0, 3, G5Q1A, G5Q1B, G5Q1C, G5Q1C, G5Q1H
	quizq G5Q2, 0, 3, G5Q2A, G5Q2B, G5Q2C, G5Q2C, G5Q2H
	quizq G5Q3, 0, 3, G5Q3A, G5Q3B, G5Q3C, G5Q3C, G5Q3H
	quizq G5Q4, 0, 3, G5Q4A, G5Q4B, G5Q4C, G5Q4C, G5Q4H
	quizq G5Q5, 0, 3, G5Q5A, G5Q5B, G5Q5C, G5Q5C, G5Q5H
	quizq G5Q6, 0, 3, G5Q6A, G5Q6B, G5Q6C, G5Q6C, G5Q6H
	quizq G5Q7, 0, 3, G5Q7A, G5Q7B, G5Q7C, G5Q7C, G5Q7H
	quizq G5Q8, 0, 3, G5Q8A, G5Q8B, G5Q8C, G5Q8C, G5Q8H
	quizq G5Q9, 0, 3, G5Q9A, G5Q9B, G5Q9C, G5Q9C, G5Q9H
	quizq G5Q10, 0, 3, G5Q10A, G5Q10B, G5Q10C, G5Q10C, G5Q10H
	quizq G5Q11, 0, 3, G5Q11A, G5Q11B, G5Q11C, G5Q11C, G5Q11H
	quizq G5Q12, 0, 3, G5Q12A, G5Q12B, G5Q12C, G5Q12C, G5Q12H
	quizq G5Q13, 0, 3, G5Q13A, G5Q13B, G5Q13C, G5Q13C, G5Q13H
	quizq G5Q14, 0, 3, G5Q14A, G5Q14B, G5Q14C, G5Q14C, G5Q14H
	quizq G5Q15, 0, 3, G5Q15A, G5Q15B, G5Q15C, G5Q15C, G5Q15H
	quizq G5Q16, 0, 3, G5Q16A, G5Q16B, G5Q16C, G5Q16C, G5Q16H
	quizq G5Q17, 0, 3, G5Q17A, G5Q17B, G5Q17C, G5Q17C, G5Q17H
	quizq G5Q18, 0, 3, G5Q18A, G5Q18B, G5Q18C, G5Q18C, G5Q18H
	quizq G5Q19, 0, 3, G5Q19A, G5Q19B, G5Q19C, G5Q19C, G5Q19H
QuestionsEnd::

; ---- strings ----
; Grade 1
G1Q1: db "1 plus 1?@"
G1Q1A: db "2@"
G1Q1B: db "1@"
G1Q1C: db "3@"
G1Q1H: db "Count on from 1@"
G1Q2: db "1 plus 2?@"
G1Q2A: db "3@"
G1Q2B: db "2@"
G1Q2C: db "4@"
G1Q2H: db "Count on from 1@"
G1Q3: db "1 plus 3?@"
G1Q3A: db "4@"
G1Q3B: db "3@"
G1Q3C: db "5@"
G1Q3H: db "Count on from 1@"
G1Q4: db "1 plus 4?@"
G1Q4A: db "5@"
G1Q4B: db "4@"
G1Q4C: db "6@"
G1Q4H: db "Count on from 1@"
G1Q5: db "1 plus 5?@"
G1Q5A: db "6@"
G1Q5B: db "5@"
G1Q5C: db "7@"
G1Q5H: db "Count on from 1@"
G1Q6: db "1 plus 6?@"
G1Q6A: db "7@"
G1Q6B: db "6@"
G1Q6C: db "8@"
G1Q6H: db "Count on from 1@"
G1Q7: db "1 plus 7?@"
G1Q7A: db "8@"
G1Q7B: db "7@"
G1Q7C: db "9@"
G1Q7H: db "Count on from 1@"
G1Q8: db "1 plus 8?@"
G1Q8A: db "9@"
G1Q8B: db "8@"
G1Q8C: db "10@"
G1Q8H: db "Count on from 1@"
G1Q9: db "1 plus 9?@"
G1Q9A: db "10@"
G1Q9B: db "9@"
G1Q9C: db "11@"
G1Q9H: db "Count on from 1@"
G1Q10: db "2 plus 1?@"
G1Q10A: db "3@"
G1Q10B: db "2@"
G1Q10C: db "4@"
G1Q10H: db "Count on from 2@"
G1Q11: db "2 plus 2?@"
G1Q11A: db "4@"
G1Q11B: db "3@"
G1Q11C: db "5@"
G1Q11H: db "Count on from 2@"
G1Q12: db "2 plus 3?@"
G1Q12A: db "5@"
G1Q12B: db "4@"
G1Q12C: db "6@"
G1Q12H: db "Count on from 2@"
G1Q13: db "2 plus 4?@"
G1Q13A: db "6@"
G1Q13B: db "5@"
G1Q13C: db "7@"
G1Q13H: db "Count on from 2@"
G1Q14: db "2 plus 5?@"
G1Q14A: db "7@"
G1Q14B: db "6@"
G1Q14C: db "8@"
G1Q14H: db "Count on from 2@"
G1Q15: db "2 plus 6?@"
G1Q15A: db "8@"
G1Q15B: db "7@"
G1Q15C: db "9@"
G1Q15H: db "Count on from 2@"
G1Q16: db "2 plus 7?@"
G1Q16A: db "9@"
G1Q16B: db "8@"
G1Q16C: db "10@"
G1Q16H: db "Count on from 2@"
G1Q17: db "2 plus 8?@"
G1Q17A: db "10@"
G1Q17B: db "9@"
G1Q17C: db "11@"
G1Q17H: db "Count on from 2@"
G1Q18: db "3 plus 1?@"
G1Q18A: db "4@"
G1Q18B: db "3@"
G1Q18C: db "5@"
G1Q18H: db "Count on from 3@"
G1Q19: db "3 plus 2?@"
G1Q19A: db "5@"
G1Q19B: db "4@"
G1Q19C: db "6@"
G1Q19H: db "Count on from 3@"
G1Q20: db "3 plus 3?@"
G1Q20A: db "6@"
G1Q20B: db "5@"
G1Q20C: db "7@"
G1Q20H: db "Count on from 3@"
G1Q21: db "3 plus 4?@"
G1Q21A: db "7@"
G1Q21B: db "6@"
G1Q21C: db "8@"
G1Q21H: db "Count on from 3@"
G1Q22: db "3 plus 5?@"
G1Q22A: db "8@"
G1Q22B: db "7@"
G1Q22C: db "9@"
G1Q22H: db "Count on from 3@"
G1Q23: db "3 plus 6?@"
G1Q23A: db "9@"
G1Q23B: db "8@"
G1Q23C: db "10@"
G1Q23H: db "Count on from 3@"
G1Q24: db "3 plus 7?@"
G1Q24A: db "10@"
G1Q24B: db "9@"
G1Q24C: db "11@"
G1Q24H: db "Count on from 3@"
G1Q25: db "4 plus 1?@"
G1Q25A: db "5@"
G1Q25B: db "4@"
G1Q25C: db "6@"
G1Q25H: db "Count on from 4@"
G1Q26: db "4 plus 2?@"
G1Q26A: db "6@"
G1Q26B: db "5@"
G1Q26C: db "7@"
G1Q26H: db "Count on from 4@"
G1Q27: db "4 plus 3?@"
G1Q27A: db "7@"
G1Q27B: db "6@"
G1Q27C: db "8@"
G1Q27H: db "Count on from 4@"
G1Q28: db "4 plus 4?@"
G1Q28A: db "8@"
G1Q28B: db "7@"
G1Q28C: db "9@"
G1Q28H: db "Count on from 4@"
G1Q29: db "4 plus 5?@"
G1Q29A: db "9@"
G1Q29B: db "8@"
G1Q29C: db "10@"
G1Q29H: db "Count on from 4@"
G1Q30: db "4 plus 6?@"
G1Q30A: db "10@"
G1Q30B: db "9@"
G1Q30C: db "11@"
G1Q30H: db "Count on from 4@"
G1Q31: db "5 plus 1?@"
G1Q31A: db "6@"
G1Q31B: db "5@"
G1Q31C: db "7@"
G1Q31H: db "Count on from 5@"
G1Q32: db "5 plus 2?@"
G1Q32A: db "7@"
G1Q32B: db "6@"
G1Q32C: db "8@"
G1Q32H: db "Count on from 5@"
G1Q33: db "5 plus 3?@"
G1Q33A: db "8@"
G1Q33B: db "7@"
G1Q33C: db "9@"
G1Q33H: db "Count on from 5@"
G1Q34: db "5 plus 4?@"
G1Q34A: db "9@"
G1Q34B: db "8@"
G1Q34C: db "10@"
G1Q34H: db "Count on from 5@"
G1Q35: db "5 plus 5?@"
G1Q35A: db "10@"
G1Q35B: db "9@"
G1Q35C: db "11@"
G1Q35H: db "Count on from 5@"
G1Q36: db "6 plus 1?@"
G1Q36A: db "7@"
G1Q36B: db "6@"
G1Q36C: db "8@"
G1Q36H: db "Count on from 6@"
G1Q37: db "6 plus 2?@"
G1Q37A: db "8@"
G1Q37B: db "7@"
G1Q37C: db "9@"
G1Q37H: db "Count on from 6@"
G1Q38: db "6 plus 3?@"
G1Q38A: db "9@"
G1Q38B: db "8@"
G1Q38C: db "10@"
G1Q38H: db "Count on from 6@"
G1Q39: db "6 plus 4?@"
G1Q39A: db "10@"
G1Q39B: db "9@"
G1Q39C: db "11@"
G1Q39H: db "Count on from 6@"
G1Q40: db "7 plus 1?@"
G1Q40A: db "8@"
G1Q40B: db "7@"
G1Q40C: db "9@"
G1Q40H: db "Count on from 7@"
G1Q41: db "3 - 1?@"
G1Q41A: db "2@"
G1Q41B: db "1@"
G1Q41C: db "3@"
G1Q41H: db "1 less than 3@"
G1Q42: db "3 - 2?@"
G1Q42A: db "1@"
G1Q42B: db "0@"
G1Q42C: db "2@"
G1Q42H: db "2 less than 3@"
G1Q43: db "4 - 1?@"
G1Q43A: db "3@"
G1Q43B: db "2@"
G1Q43C: db "4@"
G1Q43H: db "1 less than 4@"
G1Q44: db "4 - 2?@"
G1Q44A: db "2@"
G1Q44B: db "1@"
G1Q44C: db "3@"
G1Q44H: db "2 less than 4@"
G1Q45: db "4 - 3?@"
G1Q45A: db "1@"
G1Q45B: db "0@"
G1Q45C: db "2@"
G1Q45H: db "3 less than 4@"
G1Q46: db "5 - 1?@"
G1Q46A: db "4@"
G1Q46B: db "3@"
G1Q46C: db "5@"
G1Q46H: db "1 less than 5@"
G1Q47: db "5 - 2?@"
G1Q47A: db "3@"
G1Q47B: db "2@"
G1Q47C: db "4@"
G1Q47H: db "2 less than 5@"
G1Q48: db "5 - 3?@"
G1Q48A: db "2@"
G1Q48B: db "1@"
G1Q48C: db "3@"
G1Q48H: db "3 less than 5@"
G1Q49: db "5 - 4?@"
G1Q49A: db "1@"
G1Q49B: db "0@"
G1Q49C: db "2@"
G1Q49H: db "4 less than 5@"
G1Q50: db "6 - 1?@"
G1Q50A: db "5@"
G1Q50B: db "4@"
G1Q50C: db "6@"
G1Q50H: db "1 less than 6@"
G1Q51: db "6 - 2?@"
G1Q51A: db "4@"
G1Q51B: db "3@"
G1Q51C: db "5@"
G1Q51H: db "2 less than 6@"
G1Q52: db "6 - 3?@"
G1Q52A: db "3@"
G1Q52B: db "2@"
G1Q52C: db "4@"
G1Q52H: db "3 less than 6@"
G1Q53: db "6 - 4?@"
G1Q53A: db "2@"
G1Q53B: db "1@"
G1Q53C: db "3@"
G1Q53H: db "4 less than 6@"
G1Q54: db "6 - 5?@"
G1Q54A: db "1@"
G1Q54B: db "0@"
G1Q54C: db "2@"
G1Q54H: db "5 less than 6@"
G1Q55: db "7 - 1?@"
G1Q55A: db "6@"
G1Q55B: db "5@"
G1Q55C: db "7@"
G1Q55H: db "1 less than 7@"
G1Q56: db "7 - 2?@"
G1Q56A: db "5@"
G1Q56B: db "4@"
G1Q56C: db "6@"
G1Q56H: db "2 less than 7@"
G1Q57: db "7 - 3?@"
G1Q57A: db "4@"
G1Q57B: db "3@"
G1Q57C: db "5@"
G1Q57H: db "3 less than 7@"
G1Q58: db "7 - 4?@"
G1Q58A: db "3@"
G1Q58B: db "2@"
G1Q58C: db "4@"
G1Q58H: db "4 less than 7@"
G1Q59: db "7 - 5?@"
G1Q59A: db "2@"
G1Q59B: db "1@"
G1Q59C: db "3@"
G1Q59H: db "5 less than 7@"
G1Q60: db "7 - 6?@"
G1Q60A: db "1@"
G1Q60B: db "0@"
G1Q60C: db "2@"
G1Q60H: db "6 less than 7@"
G1Q61: db "8 - 1?@"
G1Q61A: db "7@"
G1Q61B: db "6@"
G1Q61C: db "8@"
G1Q61H: db "1 less than 8@"
G1Q62: db "8 - 2?@"
G1Q62A: db "6@"
G1Q62B: db "5@"
G1Q62C: db "7@"
G1Q62H: db "2 less than 8@"
G1Q63: db "8 - 3?@"
G1Q63A: db "5@"
G1Q63B: db "4@"
G1Q63C: db "6@"
G1Q63H: db "3 less than 8@"
G1Q64: db "8 - 4?@"
G1Q64A: db "4@"
G1Q64B: db "3@"
G1Q64C: db "5@"
G1Q64H: db "4 less than 8@"
G1Q65: db "8 - 5?@"
G1Q65A: db "3@"
G1Q65B: db "2@"
G1Q65C: db "4@"
G1Q65H: db "5 less than 8@"
G1Q66: db "8 - 6?@"
G1Q66A: db "2@"
G1Q66B: db "1@"
G1Q66C: db "3@"
G1Q66H: db "6 less than 8@"
G1Q67: db "8 - 7?@"
G1Q67A: db "1@"
G1Q67B: db "0@"
G1Q67C: db "2@"
G1Q67H: db "7 less than 8@"
G1Q68: db "9 - 1?@"
G1Q68A: db "8@"
G1Q68B: db "7@"
G1Q68C: db "9@"
G1Q68H: db "1 less than 9@"
G1Q69: db "9 - 2?@"
G1Q69A: db "7@"
G1Q69B: db "6@"
G1Q69C: db "8@"
G1Q69H: db "2 less than 9@"
G1Q70: db "9 - 3?@"
G1Q70A: db "6@"
G1Q70B: db "5@"
G1Q70C: db "7@"
G1Q70H: db "3 less than 9@"
G1Q71: db "9 - 4?@"
G1Q71A: db "5@"
G1Q71B: db "4@"
G1Q71C: db "6@"
G1Q71H: db "4 less than 9@"
G1Q72: db "9 - 5?@"
G1Q72A: db "4@"
G1Q72B: db "3@"
G1Q72C: db "5@"
G1Q72H: db "5 less than 9@"
G1Q73: db "9 - 6?@"
G1Q73A: db "3@"
G1Q73B: db "2@"
G1Q73C: db "4@"
G1Q73H: db "6 less than 9@"
G1Q74: db "9 - 7?@"
G1Q74A: db "2@"
G1Q74B: db "1@"
G1Q74C: db "3@"
G1Q74H: db "7 less than 9@"
G1Q75: db "9 - 8?@"
G1Q75A: db "1@"
G1Q75B: db "0@"
G1Q75C: db "2@"
G1Q75H: db "8 less than 9@"
G1Q76: db "10 - 1?@"
G1Q76A: db "9@"
G1Q76B: db "8@"
G1Q76C: db "10@"
G1Q76H: db "1 less than 10@"
G1Q77: db "10 - 2?@"
G1Q77A: db "8@"
G1Q77B: db "7@"
G1Q77C: db "9@"
G1Q77H: db "2 less than 10@"
G1Q78: db "10 - 3?@"
G1Q78A: db "7@"
G1Q78B: db "6@"
G1Q78C: db "8@"
G1Q78H: db "3 less than 10@"
G1Q79: db "10 - 4?@"
G1Q79A: db "6@"
G1Q79B: db "5@"
G1Q79C: db "7@"
G1Q79H: db "4 less than 10@"
G1Q80: db "10 - 5?@"
G1Q80A: db "5@"
G1Q80B: db "4@"
G1Q80C: db "6@"
G1Q80H: db "5 less than 10@"
G1Q81: db "10 - 6?@"
G1Q81A: db "4@"
G1Q81B: db "3@"
G1Q81C: db "5@"
G1Q81H: db "6 less than 10@"
G1Q82: db "10 - 7?@"
G1Q82A: db "3@"
G1Q82B: db "2@"
G1Q82C: db "4@"
G1Q82H: db "7 less than 10@"
G1Q83: db "10 - 8?@"
G1Q83A: db "2@"
G1Q83B: db "1@"
G1Q83C: db "3@"
G1Q83H: db "8 less than 10@"
G1Q84: db "10 - 9?@"
G1Q84A: db "1@"
G1Q84B: db "0@"
G1Q84C: db "2@"
G1Q84H: db "9 less than 10@"
G1Q85: db "2 plus 2?@"
G1Q85A: db "4@"
G1Q85B: db "3@"
G1Q85C: db "5@"
G1Q85H: db "Double of 2@"
G1Q86: db "3 plus 3?@"
G1Q86A: db "6@"
G1Q86B: db "5@"
G1Q86C: db "7@"
G1Q86H: db "Double of 3@"
G1Q87: db "4 plus 4?@"
G1Q87A: db "8@"
G1Q87B: db "7@"
G1Q87C: db "9@"
G1Q87H: db "Double of 4@"
G1Q88: db "5 plus 5?@"
G1Q88A: db "10@"
G1Q88B: db "9@"
G1Q88C: db "11@"
G1Q88H: db "Double of 5@"
G1Q89: db "Next: 1 2 3 ?@"
G1Q89A: db "4@"
G1Q89B: db "3@"
G1Q89C: db "5@"
G1Q89H: db "Count by 1@"
G1Q90: db "Next: 3 4 5 ?@"
G1Q90A: db "6@"
G1Q90B: db "5@"
G1Q90C: db "7@"
G1Q90H: db "Count by 1@"
G1Q91: db "Next: 2 4 6 ?@"
G1Q91A: db "8@"
G1Q91B: db "7@"
G1Q91C: db "9@"
G1Q91H: db "Skip count by 2@"
G1Q92: db "Next: 5 6 7 ?@"
G1Q92A: db "8@"
G1Q92B: db "7@"
G1Q92C: db "9@"
G1Q92H: db "Count by 1@"
G1Q93: db "1 more than 9?@"
G1Q93A: db "10@"
G1Q93B: db "9@"
G1Q93C: db "11@"
G1Q93H: db "Count on 1@"
; Grade 2
G2Q1: db "14 plus 8?@"
G2Q1A: db "22@"
G2Q1B: db "21@"
G2Q1C: db "23@"
G2Q1H: db "Add tens then ones@"
G2Q2: db "23 plus 9?@"
G2Q2A: db "32@"
G2Q2B: db "31@"
G2Q2C: db "33@"
G2Q2H: db "Add tens then ones@"
G2Q3: db "36 plus 7?@"
G2Q3A: db "43@"
G2Q3B: db "42@"
G2Q3C: db "44@"
G2Q3H: db "Add tens then ones@"
G2Q4: db "45 plus 6?@"
G2Q4A: db "51@"
G2Q4B: db "50@"
G2Q4C: db "52@"
G2Q4H: db "Add tens then ones@"
G2Q5: db "28 plus 14?@"
G2Q5A: db "42@"
G2Q5B: db "41@"
G2Q5C: db "43@"
G2Q5H: db "Add tens then ones@"
G2Q6: db "52 plus 19?@"
G2Q6A: db "71@"
G2Q6B: db "70@"
G2Q6C: db "72@"
G2Q6H: db "Add tens then ones@"
G2Q7: db "33 plus 27?@"
G2Q7A: db "60@"
G2Q7B: db "59@"
G2Q7C: db "61@"
G2Q7H: db "Add tens then ones@"
G2Q8: db "40 plus 35?@"
G2Q8A: db "75@"
G2Q8B: db "74@"
G2Q8C: db "76@"
G2Q8H: db "Add tens then ones@"
G2Q9: db "17 plus 18?@"
G2Q9A: db "35@"
G2Q9B: db "34@"
G2Q9C: db "36@"
G2Q9H: db "Add tens then ones@"
G2Q10: db "60 plus 25?@"
G2Q10A: db "85@"
G2Q10B: db "84@"
G2Q10C: db "86@"
G2Q10H: db "Add tens then ones@"
G2Q11: db "30 - 12?@"
G2Q11A: db "18@"
G2Q11B: db "17@"
G2Q11C: db "19@"
G2Q11H: db "Tens then ones@"
G2Q12: db "50 - 25?@"
G2Q12A: db "25@"
G2Q12B: db "24@"
G2Q12C: db "26@"
G2Q12H: db "Tens then ones@"
G2Q13: db "62 - 17?@"
G2Q13A: db "45@"
G2Q13B: db "44@"
G2Q13C: db "46@"
G2Q13H: db "Tens then ones@"
G2Q14: db "45 - 19?@"
G2Q14A: db "26@"
G2Q14B: db "25@"
G2Q14C: db "27@"
G2Q14H: db "Tens then ones@"
G2Q15: db "80 - 36?@"
G2Q15A: db "44@"
G2Q15B: db "43@"
G2Q15C: db "45@"
G2Q15H: db "Tens then ones@"
G2Q16: db "74 - 8?@"
G2Q16A: db "66@"
G2Q16B: db "65@"
G2Q16C: db "67@"
G2Q16H: db "Tens then ones@"
G2Q17: db "90 - 45?@"
G2Q17A: db "45@"
G2Q17B: db "44@"
G2Q17C: db "46@"
G2Q17H: db "Tens then ones@"
G2Q18: db "Tens in 20?@"
G2Q18A: db "2@"
G2Q18B: db "1@"
G2Q18C: db "3@"
G2Q18H: db "20 is 2 tens@"
G2Q19: db "Tens in 30?@"
G2Q19A: db "3@"
G2Q19B: db "2@"
G2Q19C: db "4@"
G2Q19H: db "30 is 3 tens@"
G2Q20: db "Tens in 40?@"
G2Q20A: db "4@"
G2Q20B: db "3@"
G2Q20C: db "5@"
G2Q20H: db "40 is 4 tens@"
G2Q21: db "Tens in 50?@"
G2Q21A: db "5@"
G2Q21B: db "4@"
G2Q21C: db "6@"
G2Q21H: db "50 is 5 tens@"
G2Q22: db "Tens in 60?@"
G2Q22A: db "6@"
G2Q22B: db "5@"
G2Q22C: db "7@"
G2Q22H: db "60 is 6 tens@"
G2Q23: db "Tens in 70?@"
G2Q23A: db "7@"
G2Q23B: db "6@"
G2Q23C: db "8@"
G2Q23H: db "70 is 7 tens@"
G2Q24: db "Tens in 80?@"
G2Q24A: db "8@"
G2Q24B: db "7@"
G2Q24C: db "9@"
G2Q24H: db "80 is 8 tens@"
G2Q25: db "Tens in 90?@"
G2Q25A: db "9@"
G2Q25B: db "8@"
G2Q25C: db "10@"
G2Q25H: db "90 is 9 tens@"
G2Q26: db "6 plus 6?@"
G2Q26A: db "12@"
G2Q26B: db "11@"
G2Q26C: db "13@"
G2Q26H: db "Double of 6@"
G2Q27: db "7 plus 7?@"
G2Q27A: db "14@"
G2Q27B: db "13@"
G2Q27C: db "15@"
G2Q27H: db "Double of 7@"
G2Q28: db "8 plus 8?@"
G2Q28A: db "16@"
G2Q28B: db "15@"
G2Q28C: db "17@"
G2Q28H: db "Double of 8@"
G2Q29: db "9 plus 9?@"
G2Q29A: db "18@"
G2Q29B: db "17@"
G2Q29C: db "19@"
G2Q29H: db "Double of 9@"
G2Q30: db "Add three 4s@"
G2Q30A: db "12@"
G2Q30B: db "11@"
G2Q30C: db "13@"
G2Q30H: db "4 plus 4 plus 4@"
G2Q31: db "Add three 5s@"
G2Q31A: db "15@"
G2Q31B: db "14@"
G2Q31C: db "16@"
G2Q31H: db "5 plus 5 plus 5@"
G2Q32: db "Add three 6s@"
G2Q32A: db "18@"
G2Q32B: db "17@"
G2Q32C: db "19@"
G2Q32H: db "6 plus 6 plus 6@"
; Grade 3
G3Q1: db "2 x 2?@"
G3Q1A: db "4@"
G3Q1B: db "3@"
G3Q1C: db "5@"
G3Q1H: db "2 groups of 2@"
G3Q2: db "2 x 3?@"
G3Q2A: db "6@"
G3Q2B: db "5@"
G3Q2C: db "7@"
G3Q2H: db "2 groups of 3@"
G3Q3: db "2 x 4?@"
G3Q3A: db "8@"
G3Q3B: db "7@"
G3Q3C: db "9@"
G3Q3H: db "2 groups of 4@"
G3Q4: db "2 x 5?@"
G3Q4A: db "10@"
G3Q4B: db "9@"
G3Q4C: db "11@"
G3Q4H: db "2 groups of 5@"
G3Q5: db "2 x 6?@"
G3Q5A: db "12@"
G3Q5B: db "11@"
G3Q5C: db "13@"
G3Q5H: db "2 groups of 6@"
G3Q6: db "2 x 7?@"
G3Q6A: db "14@"
G3Q6B: db "13@"
G3Q6C: db "15@"
G3Q6H: db "2 groups of 7@"
G3Q7: db "2 x 8?@"
G3Q7A: db "16@"
G3Q7B: db "15@"
G3Q7C: db "17@"
G3Q7H: db "2 groups of 8@"
G3Q8: db "2 x 9?@"
G3Q8A: db "18@"
G3Q8B: db "17@"
G3Q8C: db "19@"
G3Q8H: db "2 groups of 9@"
G3Q9: db "3 x 3?@"
G3Q9A: db "9@"
G3Q9B: db "8@"
G3Q9C: db "10@"
G3Q9H: db "3 groups of 3@"
G3Q10: db "3 x 4?@"
G3Q10A: db "12@"
G3Q10B: db "11@"
G3Q10C: db "13@"
G3Q10H: db "3 groups of 4@"
G3Q11: db "3 x 5?@"
G3Q11A: db "15@"
G3Q11B: db "14@"
G3Q11C: db "16@"
G3Q11H: db "3 groups of 5@"
G3Q12: db "3 x 6?@"
G3Q12A: db "18@"
G3Q12B: db "17@"
G3Q12C: db "19@"
G3Q12H: db "3 groups of 6@"
G3Q13: db "3 x 7?@"
G3Q13A: db "21@"
G3Q13B: db "20@"
G3Q13C: db "22@"
G3Q13H: db "3 groups of 7@"
G3Q14: db "3 x 8?@"
G3Q14A: db "24@"
G3Q14B: db "23@"
G3Q14C: db "25@"
G3Q14H: db "3 groups of 8@"
G3Q15: db "3 x 9?@"
G3Q15A: db "27@"
G3Q15B: db "26@"
G3Q15C: db "28@"
G3Q15H: db "3 groups of 9@"
G3Q16: db "4 x 4?@"
G3Q16A: db "16@"
G3Q16B: db "15@"
G3Q16C: db "17@"
G3Q16H: db "4 groups of 4@"
G3Q17: db "4 x 5?@"
G3Q17A: db "20@"
G3Q17B: db "19@"
G3Q17C: db "21@"
G3Q17H: db "4 groups of 5@"
G3Q18: db "4 x 6?@"
G3Q18A: db "24@"
G3Q18B: db "23@"
G3Q18C: db "25@"
G3Q18H: db "4 groups of 6@"
G3Q19: db "4 x 7?@"
G3Q19A: db "28@"
G3Q19B: db "27@"
G3Q19C: db "29@"
G3Q19H: db "4 groups of 7@"
G3Q20: db "4 x 8?@"
G3Q20A: db "32@"
G3Q20B: db "31@"
G3Q20C: db "33@"
G3Q20H: db "4 groups of 8@"
G3Q21: db "4 x 9?@"
G3Q21A: db "36@"
G3Q21B: db "35@"
G3Q21C: db "37@"
G3Q21H: db "4 groups of 9@"
G3Q22: db "5 x 5?@"
G3Q22A: db "25@"
G3Q22B: db "24@"
G3Q22C: db "26@"
G3Q22H: db "5 groups of 5@"
G3Q23: db "5 x 6?@"
G3Q23A: db "30@"
G3Q23B: db "29@"
G3Q23C: db "31@"
G3Q23H: db "5 groups of 6@"
G3Q24: db "5 x 7?@"
G3Q24A: db "35@"
G3Q24B: db "34@"
G3Q24C: db "36@"
G3Q24H: db "5 groups of 7@"
G3Q25: db "5 x 8?@"
G3Q25A: db "40@"
G3Q25B: db "39@"
G3Q25C: db "41@"
G3Q25H: db "5 groups of 8@"
G3Q26: db "5 x 9?@"
G3Q26A: db "45@"
G3Q26B: db "44@"
G3Q26C: db "46@"
G3Q26H: db "5 groups of 9@"
G3Q27: db "6 x 6?@"
G3Q27A: db "36@"
G3Q27B: db "35@"
G3Q27C: db "37@"
G3Q27H: db "6 groups of 6@"
G3Q28: db "6 x 7?@"
G3Q28A: db "42@"
G3Q28B: db "41@"
G3Q28C: db "43@"
G3Q28H: db "6 groups of 7@"
G3Q29: db "6 x 8?@"
G3Q29A: db "48@"
G3Q29B: db "47@"
G3Q29C: db "49@"
G3Q29H: db "6 groups of 8@"
G3Q30: db "6 x 9?@"
G3Q30A: db "54@"
G3Q30B: db "53@"
G3Q30C: db "55@"
G3Q30H: db "6 groups of 9@"
G3Q31: db "7 x 7?@"
G3Q31A: db "49@"
G3Q31B: db "48@"
G3Q31C: db "50@"
G3Q31H: db "7 groups of 7@"
G3Q32: db "7 x 8?@"
G3Q32A: db "56@"
G3Q32B: db "55@"
G3Q32C: db "57@"
G3Q32H: db "7 groups of 8@"
G3Q33: db "7 x 9?@"
G3Q33A: db "63@"
G3Q33B: db "62@"
G3Q33C: db "64@"
G3Q33H: db "7 groups of 9@"
G3Q34: db "8 x 8?@"
G3Q34A: db "64@"
G3Q34B: db "63@"
G3Q34C: db "65@"
G3Q34H: db "8 groups of 8@"
G3Q35: db "8 x 9?@"
G3Q35A: db "72@"
G3Q35B: db "71@"
G3Q35C: db "73@"
G3Q35H: db "8 groups of 9@"
G3Q36: db "9 x 9?@"
G3Q36A: db "81@"
G3Q36B: db "80@"
G3Q36C: db "82@"
G3Q36H: db "9 groups of 9@"
G3Q37: db "24 / 4?@"
G3Q37A: db "6@"
G3Q37B: db "5@"
G3Q37C: db "7@"
G3Q37H: db "4 x what is 24@"
G3Q38: db "36 / 6?@"
G3Q38A: db "6@"
G3Q38B: db "5@"
G3Q38C: db "7@"
G3Q38H: db "6 x what is 36@"
G3Q39: db "42 / 7?@"
G3Q39A: db "6@"
G3Q39B: db "5@"
G3Q39C: db "7@"
G3Q39H: db "7 x what is 42@"
G3Q40: db "48 / 8?@"
G3Q40A: db "6@"
G3Q40B: db "5@"
G3Q40C: db "7@"
G3Q40H: db "8 x what is 48@"
G3Q41: db "54 / 9?@"
G3Q41A: db "6@"
G3Q41B: db "5@"
G3Q41C: db "7@"
G3Q41H: db "9 x what is 54@"
G3Q42: db "63 / 9?@"
G3Q42A: db "7@"
G3Q42B: db "6@"
G3Q42C: db "8@"
G3Q42H: db "9 x what is 63@"
G3Q43: db "40 / 5?@"
G3Q43A: db "8@"
G3Q43B: db "7@"
G3Q43C: db "9@"
G3Q43H: db "5 x what is 40@"
G3Q44: db "56 / 8?@"
G3Q44A: db "7@"
G3Q44B: db "6@"
G3Q44C: db "8@"
G3Q44H: db "8 x what is 56@"
G3Q45: db "Half of 10?@"
G3Q45A: db "5@"
G3Q45B: db "4@"
G3Q45C: db "6@"
G3Q45H: db "Split 10 in two@"
G3Q46: db "Half of 12?@"
G3Q46A: db "6@"
G3Q46B: db "5@"
G3Q46C: db "7@"
G3Q46H: db "Split 12 in two@"
G3Q47: db "Half of 14?@"
G3Q47A: db "7@"
G3Q47B: db "6@"
G3Q47C: db "8@"
G3Q47H: db "Split 14 in two@"
G3Q48: db "Half of 16?@"
G3Q48A: db "8@"
G3Q48B: db "7@"
G3Q48C: db "9@"
G3Q48H: db "Split 16 in two@"
G3Q49: db "Half of 18?@"
G3Q49A: db "9@"
G3Q49B: db "8@"
G3Q49C: db "10@"
G3Q49H: db "Split 18 in two@"
G3Q50: db "Half of 20?@"
G3Q50A: db "10@"
G3Q50B: db "9@"
G3Q50C: db "11@"
G3Q50H: db "Split 20 in two@"
; Grade 4
G4Q1: db "11 x 11?@"
G4Q1A: db "121@"
G4Q1B: db "120@"
G4Q1C: db "122@"
G4Q1H: db "Break 11 apart@"
G4Q2: db "12 x 12?@"
G4Q2A: db "144@"
G4Q2B: db "143@"
G4Q2C: db "145@"
G4Q2H: db "Break 12 apart@"
G4Q3: db "13 x 11?@"
G4Q3A: db "143@"
G4Q3B: db "142@"
G4Q3C: db "144@"
G4Q3H: db "Break 11 apart@"
G4Q4: db "11 x 9?@"
G4Q4A: db "99@"
G4Q4B: db "98@"
G4Q4C: db "100@"
G4Q4H: db "Break 9 apart@"
G4Q5: db "12 x 8?@"
G4Q5A: db "96@"
G4Q5B: db "95@"
G4Q5C: db "97@"
G4Q5H: db "Break 8 apart@"
G4Q6: db "15 x 6?@"
G4Q6A: db "90@"
G4Q6B: db "89@"
G4Q6C: db "91@"
G4Q6H: db "Break 6 apart@"
G4Q7: db "14 x 5?@"
G4Q7A: db "70@"
G4Q7B: db "69@"
G4Q7C: db "71@"
G4Q7H: db "Break 5 apart@"
G4Q8: db "11 x 7?@"
G4Q8A: db "77@"
G4Q8B: db "76@"
G4Q8C: db "78@"
G4Q8H: db "Break 7 apart@"
G4Q9: db "144 / 12?@"
G4Q9A: db "12@"
G4Q9B: db "11@"
G4Q9C: db "13@"
G4Q9H: db "12 x what is 144@"
G4Q10: db "100 / 4?@"
G4Q10A: db "25@"
G4Q10B: db "24@"
G4Q10C: db "26@"
G4Q10H: db "4 x what is 100@"
G4Q11: db "121 / 11?@"
G4Q11A: db "11@"
G4Q11B: db "10@"
G4Q11C: db "12@"
G4Q11H: db "11 x what is 121@"
G4Q12: db "90 / 6?@"
G4Q12A: db "15@"
G4Q12B: db "14@"
G4Q12C: db "16@"
G4Q12H: db "6 x what is 90@"
G4Q13: db "96 / 8?@"
G4Q13A: db "12@"
G4Q13B: db "11@"
G4Q13C: db "13@"
G4Q13H: db "8 x what is 96@"
G4Q14: db "132 / 12?@"
G4Q14A: db "11@"
G4Q14B: db "10@"
G4Q14C: db "12@"
G4Q14H: db "12 x what is 132@"
G4Q15: db "2/4 equals?@"
G4Q15A: db "1/2@"
G4Q15B: db "1/3@"
G4Q15C: db "1/4@"
G4Q15H: db "Top and bottom /2@"
G4Q16: db "3/6 equals?@"
G4Q16A: db "1/2@"
G4Q16B: db "1/3@"
G4Q16C: db "2/6@"
G4Q16H: db "Both halve to 1/2@"
G4Q17: db "3/4 of 8?@"
G4Q17A: db "6@"
G4Q17B: db "5@"
G4Q17C: db "7@"
G4Q17H: db "8 /4 then x3@"
G4Q18: db "1/2 of 10?@"
G4Q18A: db "5@"
G4Q18B: db "4@"
G4Q18C: db "6@"
G4Q18H: db "Split 10 in two@"
G4Q19: db "Half of 1.0?@"
G4Q19A: db "0.5@"
G4Q19B: db "0.2@"
G4Q19C: db "5.0@"
G4Q19H: db "1.0 split in two@"
G4Q20: db "Half of 5.0?@"
G4Q20A: db "2.5@"
G4Q20B: db "2.0@"
G4Q20C: db "3.0@"
G4Q20H: db "5.0 split in two@"
G4Q21: db "0.5 plus 0.5?@"
G4Q21A: db "1.0@"
G4Q21B: db "0.5@"
G4Q21C: db "1.5@"
G4Q21H: db "Two halves make 1@"
; Grade 5
G5Q1: db "2 plus 3 x 4?@"
G5Q1A: db "14@"
G5Q1B: db "13@"
G5Q1C: db "15@"
G5Q1H: db "Times before plus@"
G5Q2: db "5 plus 2 x 3?@"
G5Q2A: db "11@"
G5Q2B: db "10@"
G5Q2C: db "12@"
G5Q2H: db "Times before plus@"
G5Q3: db "1 plus 6 x 2?@"
G5Q3A: db "13@"
G5Q3B: db "12@"
G5Q3C: db "14@"
G5Q3H: db "Times before plus@"
G5Q4: db "4 plus 4 x 2?@"
G5Q4A: db "12@"
G5Q4B: db "11@"
G5Q4C: db "13@"
G5Q4H: db "Times before plus@"
G5Q5: db "7 plus 2 x 5?@"
G5Q5A: db "17@"
G5Q5B: db "16@"
G5Q5C: db "18@"
G5Q5H: db "Times before plus@"
G5Q6: db "10 - 2 x 3?@"
G5Q6A: db "4@"
G5Q6B: db "3@"
G5Q6C: db "5@"
G5Q6H: db "Times first@"
G5Q7: db "20 - 3 x 4?@"
G5Q7A: db "8@"
G5Q7B: db "7@"
G5Q7C: db "9@"
G5Q7H: db "Times first@"
G5Q8: db "15 - 2 x 2?@"
G5Q8A: db "11@"
G5Q8B: db "10@"
G5Q8C: db "12@"
G5Q8H: db "Times first@"
G5Q9: db "12 - 1 x 5?@"
G5Q9A: db "7@"
G5Q9B: db "6@"
G5Q9C: db "8@"
G5Q9H: db "Times first@"
G5Q10: db "0.6 plus 0.7?@"
G5Q10A: db "1.3@"
G5Q10B: db "1.2@"
G5Q10C: db "0.13@"
G5Q10H: db "Add tenths 6 and 7@"
G5Q11: db "0.4 plus 0.5?@"
G5Q11A: db "0.9@"
G5Q11B: db "0.8@"
G5Q11C: db "1.0@"
G5Q11H: db "Add the tenths@"
G5Q12: db "0.8 plus 0.3?@"
G5Q12A: db "1.1@"
G5Q12B: db "1.0@"
G5Q12C: db "0.11@"
G5Q12H: db "Add tenths 8 and 3@"
G5Q13: db "3/4 plus 1/4?@"
G5Q13A: db "1@"
G5Q13B: db "4/8@"
G5Q13C: db "2@"
G5Q13H: db "Add tops: 3 plus 1@"
G5Q14: db "1/2 plus 1/4?@"
G5Q14A: db "3/4@"
G5Q14B: db "1/4@"
G5Q14C: db "2/4@"
G5Q14H: db "1/2 is 2/4@"
G5Q15: db "2/5 plus 1/5?@"
G5Q15A: db "3/5@"
G5Q15B: db "3/10@"
G5Q15C: db "1/5@"
G5Q15H: db "Add tops: 2 plus 1@"
G5Q16: db "Round 4.7?@"
G5Q16A: db "5@"
G5Q16B: db "4@"
G5Q16C: db "6@"
G5Q16H: db ".5 or more goes up@"
G5Q17: db "Round 5.5?@"
G5Q17A: db "6@"
G5Q17B: db "5@"
G5Q17C: db "7@"
G5Q17H: db ".5 rounds up@"
G5Q18: db "Round 3.2?@"
G5Q18A: db "3@"
G5Q18B: db "4@"
G5Q18C: db "2@"
G5Q18H: db "Under .5 stays@"
G5Q19: db "Round 8.9?@"
G5Q19A: db "9@"
G5Q19B: db "8@"
G5Q19C: db "10@"
G5Q19H: db "Close to 9@"

; ---- result messages (shown via PrintText) ----
QuizCorrectText::
	text "Great job!"
	line "Streak "
	text_ram wStringBuffer
	prompt

QuizTryAgainText::
	text "Hint:"
	line ""
	text_ram wStringBuffer
	cont "Try once more!"
	prompt

QuizMissText::
	text "The answer was"
	line ""
	text_ram wStringBuffer
	cont "Now you know!"
	prompt
