// Offline renderer: capture the game's OWN music straight from the ROM into
// short, seamless, standalone audio loops, so the player can play the real
// Pokemon Red music as an INDEPENDENT track -- decoupled from the emulator's
// speed, so it never speeds up during fast-forward.
//
// How it works (headless, no browser):
//   1. Boot the real pokered.gbc in binjgb and run a few seconds to the title
//      screen, where the LCD is on and interrupts are enabled (so the V-blank
//      handler -- which is what advances the music every frame -- keeps firing).
//   2. Inject a tiny stub into wOverworldMap (0xc6e8, a big buffer that's empty
//      at the title screen and never touched by V-blank):
//          ld a, <songId> ; ld c, <audioBank> ; call PlayMusic ; jr -2
//      and point the CPU at it. PlayMusic starts the chosen song; the CPU then
//      idles in the 2-byte loop while the V-blank interrupt advances the music.
//   3. Record binjgb's emulated audio for ~30s, downmix to 8-bit mono.
//   4. Find the exact loop period by cross-correlation (the sound engine is
//      deterministic, so the waveform repeats almost bit-for-bit) and keep one
//      seamless loop. Gzip the PCM and write vendor/music_data.js (base64).
//
// The runtime engine (MUSIC_JS in build_player.py) decodes these and loops the
// one matching the live game context. No new audio is synthesized; this is the
// game's own soundtrack, captured once at build time.
//
// Run:  node render_music.js [path/to/pokered.gbc] [out/music_data.js]
const fs = require("fs"), path = require("path"), zlib = require("zlib");
const Binjgb = require("./vendor/binjgb.js");

const ROM = process.argv[2] || path.join(__dirname, "..", "pokered", "pokered.gbc");
const OUT = process.argv[3] || path.join(__dirname, "vendor", "music_data.js");

const RATE = 22050;                 // capture/output sample rate (mono)
const TPF = 70224;                  // GB ticks per frame
const CPU_TPS = 4194304;            // GB ticks per second
const EVENT_AUDIO_BUFFER_FULL = 2, EVENT_UNTIL_TICKS = 4;
const AUDIO_FRAMES = 4096;          // frames per binjgb audio buffer
const STUB = 0xc6e8;                // wOverworldMap: free + V-blank-safe at title
const PLAYMUSIC = 0x23a1;           // home/audio.asm PlayMusic (a=id, c=audioBank)

// Context -> (song id, audio engine bank). Ids = (header_addr-0x4000)/3, banks
// are the three audio engines (Audio1=0x02, Audio2=0x08, Audio3=0x1f). All
// derived from pokered.sym; see render notes above.
const SONGS = {
  town:    { id: 0xBA, bank: 0x02 },  // Music_PalletTown
  route:   { id: 0xEB, bank: 0x02 },  // Music_Routes1
  centre:  { id: 0xBD, bank: 0x02 },  // Music_Pokecenter
  cave:    { id: 0xE0, bank: 0x1f },  // Music_Dungeon1
  wild:    { id: 0xF0, bank: 0x08 },  // Music_WildBattle
  trainer: { id: 0xED, bank: 0x08 },  // Music_TrainerBattle
  boss:    { id: 0xEA, bank: 0x08 },  // Music_GymLeaderBattle
  rival:   { id: 0xF3, bank: 0x08 },  // Music_FinalBattle
  victory: { id: 0xF6, bank: 0x08, secs: 13, loop: false }, // Music_DefeatedTrainer (one-shot jingle)
};
const DEFAULT_SECS = 36;

(async () => {
  const wasm = fs.readFileSync(path.join(__dirname, "vendor", "binjgb.wasm"));
  const rom = fs.readFileSync(ROM);
  const size = (rom.length + 0x7fff) & ~0x7fff;

  const tracks = {};
  for (const [name, cfg] of Object.entries(SONGS)) {
    const secs = cfg.secs || DEFAULT_SECS;
    const mono = await captureSong(wasm, rom, size, cfg.id, cfg.bank, secs);
    const f = new Float32Array(mono.length);
    for (let i = 0; i < mono.length; i++) f[i] = (mono[i] - 128) / 128;

    let pcm, frames, loop = cfg.loop !== false;
    if (loop) {
      const { start, period } = findLoop(f);
      pcm = bakeLoop(f, start, period);          // one period, crossfade baked in
      frames = pcm.length;
      console.log(`  ${name.padEnd(8)} ${(frames / RATE).toFixed(2)}s seamless loop`);
    } else {
      pcm = toU8(f.subarray(0, mono.length));     // one-shot jingle, played once
      frames = pcm.length;
      console.log(`  ${name.padEnd(8)} ${(frames / RATE).toFixed(2)}s one-shot`);
    }
    const gz = zlib.gzipSync(Buffer.from(pcm), { level: 9 });
    tracks[name] = { b64: gz.toString("base64"), frames: frames, loop: loop };
    console.log(`           -> ${(gz.length / 1024).toFixed(0)} KB gz`);
  }

  const payload = { rate: RATE, tracks };
  const js = "// Generated by render_music.js -- the game's own music, captured\n" +
             "// from the ROM as gzipped 8-bit mono PCM loops (base64). Do not edit.\n" +
             "window.__MUSIC_DATA = " + JSON.stringify(payload) + ";\n";
  fs.writeFileSync(OUT, js);
  const total = Object.values(tracks).reduce((s, t) => s + t.b64.length, 0);
  console.log(`Wrote ${OUT}  (${(js.length / 1024 / 1024).toFixed(2)} MB, ${Object.keys(tracks).length} tracks, ~${(total / 1024 / 1024).toFixed(2)} MB base64)`);
})().catch((e) => { console.error("render_music error:", e); process.exit(1); });

// Boot the ROM, force one song, and record `secs` seconds of mono 8-bit audio.
async function captureSong(wasm, rom, size, songId, bank, secs) {
  const m = await Binjgb({ wasmBinary: wasm });
  const romPtr = m._malloc(size);
  m.HEAPU8.fill(0, romPtr, romPtr + size);
  m.HEAPU8.set(rom, romPtr);
  const e = m._emulator_new_simple(romPtr, size, RATE, AUDIO_FRAMES, 0);
  if (e === 0) throw new Error("emulator_new_simple failed");
  const ticks = () => m._emulator_get_ticks_f64(e);
  const aptr = m._get_audio_buffer_ptr(e);

  // Run to the title screen (LCD on, interrupts enabled, audio engine live).
  runTicks(m, e, 400 * TPF);

  // Inject: ld a,id ; ld c,bank ; call PlayMusic ; jr -2  (idle loop)
  const stub = [0x3e, songId & 0xff, 0x0e, bank & 0xff,
                0xcd, PLAYMUSIC & 0xff, (PLAYMUSIC >> 8) & 0xff, 0x18, 0xfe];
  for (let i = 0; i < stub.length; i++) m._emulator_write_mem(e, STUB + i, stub[i]);
  m._emulator_set_PC(e, STUB);

  // Let the song start and settle, discarding the switch transient.
  captureMono(m, e, aptr, ticks, 1.0);
  return captureMono(m, e, aptr, ticks, secs);
}

// Advance the emulator by nTicks, servicing (and ignoring) audio/frame events.
function runTicks(m, e, nTicks) {
  const target = m._emulator_get_ticks_f64(e) + nTicks;
  while (true) {
    const ev = m._emulator_run_until_f64(e, target);
    if (ev & EVENT_UNTIL_TICKS) break;
  }
}

// Record `secs` seconds, returning a Uint8Array of mono samples (0..255).
function captureMono(m, e, aptr, ticks, secs) {
  const want = Math.ceil(secs * RATE);
  const out = new Uint8Array(want);
  let got = 0;
  const target = ticks() + Math.ceil((secs + 6) * CPU_TPS);
  while (got < want) {
    const ev = m._emulator_run_until_f64(e, target);
    if (ev & EVENT_AUDIO_BUFFER_FULL) {
      for (let i = 0; i < AUDIO_FRAMES && got < want; i++) {
        const l = m.HEAPU8[aptr + 2 * i], r = m.HEAPU8[aptr + 2 * i + 1];
        out[got++] = (l + r + 1) >> 1;          // downmix L/R, round
      }
    }
    if (ev & EVENT_UNTIL_TICKS) break;           // safety: shouldn't hit
  }
  return out.subarray(0, got);
}

// Find the musical loop period. GB percussion is the noise channel (an LFSR),
// so the raw waveform never repeats sample-for-sample -- but the melody/bass DO
// repeat. So we find the period from the loudness ENVELOPE (robust to noise) via
// normalized autocorrelation, then refine it to sample accuracy on a low-passed
// copy (which keeps the tonal content and drops the hiss). Returns {start,
// period}; the slice [start, start+period] is one musical loop.
function findLoop(f) {
  const n = f.length;
  const HOP = Math.floor(0.005 * RATE);          // 5ms -> 200 Hz envelope
  const env = envelope(f, HOP);
  const eLen = env.length;

  const refE = Math.floor(0.25 * eLen);          // reference window, past the intro
  const winE = Math.min(Math.floor(4.0 / 0.005), eLen - refE - 2); // ~4s
  const minLag = Math.floor(1.5 / 0.005);        // >= 1.5s
  const maxLag = Math.min(Math.floor(18.0 / 0.005), eLen - refE - winE - 1);

  let bestLag = minLag, bestCorr = -Infinity;
  for (let lag = minLag; lag <= maxLag; lag++) {
    const c = ncc(env, refE, refE + lag, winE);
    if (c > bestCorr) { bestCorr = c; bestLag = lag; }
  }
  let period = bestLag * HOP;                     // coarse period in samples
  console.log(`    envelope period ${(period / RATE).toFixed(2)}s (corr ${bestCorr.toFixed(3)})`);

  // Refine on a low-passed waveform (kills the noise drums) by SSD around the
  // coarse estimate at single-sample resolution.
  const lp = lowpass(f, 16);
  const start = Math.floor(0.25 * n);
  const win = Math.floor(2.0 * RATE);
  const lo = Math.max(Math.floor(1.0 * RATE), period - HOP);
  const hi = Math.min(period + HOP, n - start - win - 1);
  let bestT = period, bestSSD = Infinity;
  for (let t = lo; t <= hi; t++) {
    let s = 0;
    for (let i = 0; i < win; i += 2) { const d = lp[start + i] - lp[start + t + i]; s += d * d; }
    if (s < bestSSD) { bestSSD = s; bestT = t; }
  }
  console.log(`    refined period ${(bestT / RATE).toFixed(3)}s`);
  return { start: start, period: bestT };
}

// Short-time loudness envelope: mean |sample| over each HOP-sized window.
function envelope(f, hop) {
  const out = new Float32Array(Math.floor(f.length / hop));
  for (let k = 0; k < out.length; k++) {
    let s = 0; const base = k * hop;
    for (let i = 0; i < hop; i++) s += Math.abs(f[base + i]);
    out[k] = s / hop;
  }
  return out;
}

// Normalized cross-correlation of two equal-length windows of `a`.
function ncc(a, i0, j0, win) {
  let sa = 0, sb = 0, saa = 0, sbb = 0, sab = 0;
  for (let k = 0; k < win; k++) {
    const x = a[i0 + k], y = a[j0 + k];
    sa += x; sb += y; saa += x * x; sbb += y * y; sab += x * y;
  }
  const cov = sab - sa * sb / win;
  const va = saa - sa * sa / win, vb = sbb - sb * sb / win;
  const den = Math.sqrt(va * vb);
  return den > 1e-9 ? cov / den : 0;
}

// Simple moving-average low-pass (taps ~ RATE/cutoff); keeps melody, drops hiss.
function lowpass(f, taps) {
  const out = new Float32Array(f.length);
  let acc = 0;
  for (let i = 0; i < f.length; i++) {
    acc += f[i];
    if (i >= taps) acc -= f[i - taps];
    out[i] = acc / Math.min(i + 1, taps);
  }
  return out;
}

// Build one loop period with an equal-power crossfade baked into the head, so
// native looping is click-free despite the noise-channel mismatch at the seam.
// out[i<C] blends the loop head with the content one period later; at the wrap
// (out[L-1] -> out[0]) the original samples s+L-1 -> s+L are adjacent, so the
// transition is continuous.
function bakeLoop(f, start, period) {
  const L = period;
  const C = Math.min(Math.floor(0.06 * RATE), Math.floor(L / 4));
  const loop = new Float32Array(L);
  for (let i = 0; i < L; i++) loop[i] = f[start + i];
  for (let i = 0; i < C; i++) {
    const a = (i + 0.5) / C;                      // 0..1
    const fin = Math.sin(a * Math.PI / 2);        // equal-power fade in
    const fout = Math.cos(a * Math.PI / 2);       // ... and out
    loop[i] = f[start + i] * fin + f[start + L + i] * fout;
  }
  return toU8(loop);
}

// Float [-1,1] -> 8-bit unsigned (matches binjgb's native sample format).
function toU8(f) {
  const out = new Uint8Array(f.length);
  for (let i = 0; i < f.length; i++) {
    let v = Math.round(f[i] * 128 + 128);
    out[i] = v < 0 ? 0 : v > 255 ? 255 : v;
  }
  return out;
}
